In [386]:
from __future__ import print_function, division
import cv2
import torch
import numpy as np
import pickle
import math

In [387]:
%load_ext autoreload
%autoreload 2

from featureBA.src.model import sparse3DBA
from featureBA.src.utils import sobel_filter

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [405]:
data = pickle.load(open("toy_example/data/toyexample_1_data.p", 'rb'))
img = cv2.imread("toy_example/data/toyexample_1.png")

In [406]:
T_perturbed = np.array([[math.cos(5*math.pi/180), -math.sin(5*math.pi/180), 0, 0],
             [math.sin(5*math.pi/180), math.cos(5*math.pi/180), 0, 0],
             [0, 0, 1, 0]])

In [407]:
data['coords'] = np.around(data['2d_points']).astype(int) - 1

In [408]:
P_perturbed = np.dot(data['K'], T_perturbed)
projected_2d = np.dot(P_perturbed, np.concatenate((data['3d_points'], np.ones(len(data['3d_points']))[:, None]),-1).T)
projected_2d = (projected_2d.T/projected_2d.T[:,2,None])[:, :2]

In [409]:
coords_2d = np.around(projected_2d)
coords_2d = coords_2d.astype(int) - 1

In [410]:
data['coords'].shape , data ['3d_points'].shape

((13, 2), (13, 3))

In [411]:
img = img.astype('uint8')
for i, p in enumerate(coords_2d):
    print(i, p)
    cv2.circle(img, tuple(p), 1, (128, 128, 0), -1)

0 [32 47]
1 [37 80]
2 [54 48]
3 [72 55]
4 [89 63]
5 [76 71]
6 [56 83]
7 [61 80]
8 [49 79]
9 [40 88]
10 [108 102]
11 [94 50]
12 [64 35]


In [412]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [413]:
cv2.imwrite('perturbed_points.png', img)

True

### run BA

In [414]:
%load_ext autoreload
%autoreload 2

from featureBA.src.model import sparse3DBA
from featureBA.src.utils import sobel_filter

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [415]:
img = cv2.imread("toy_example/data/toyexample_1.png", 0)
img = img.astype('double')

In [416]:
img_torch = torch.from_numpy(img)[None,...]
grad_x, grad_y = sobel_filter(img_torch)

In [421]:
cv2.imshow('image', grad_x.numpy().reshape(img.shape).astype('uint8'))
cv2.waitKey(0)
cv2.destroyAllWindows()

In [422]:
cv2.imwrite("grad_x.png", grad_x.numpy().reshape(img.shape).astype('uint8'))
cv2.imwrite("grad_y.png", grad_y.numpy().reshape(img.shape).astype('uint8'))

True

In [425]:
pts3D = torch.from_numpy(data['3d_points'][:,:3])
ref2d = torch.from_numpy(np.flip(data['coords'], axis = 1).copy())
feature_ref = torch.cat([img_torch[:, i, j].unsqueeze(0) for i, j in zip(ref2d[:,0], ref2d[:,1])]).type(torch.DoubleTensor)
feature_map_query = img_torch.type(torch.DoubleTensor)
R_init, t_init = torch.from_numpy(T_perturbed[:, :3]), torch.from_numpy(T_perturbed[:, 3])
feature_grad_x = grad_x
feature_grad_y = grad_y
K = torch.from_numpy(data['K'])

In [426]:
from __future__ import print_function, division

from featureBA.src.utils import (from_homogeneous, to_homogeneous,
                                 batched_eye_like, skew_symmetric, so3exp_map)

from featureBA.src.utils import squared_loss, scaled_loss
import torch
from torch import nn
import numpy as np

def optimizer_step(g, H, lambda_=0):
    """One optimization step with Gauss-Newton or Levenberg-Marquardt.
    Args:
        g: batched gradient tensor of size (..., N).
        H: batched hessian tensor of size (..., N, N).
        lambda_: damping factor for LM (use GN if lambda_=0).
    """
    if lambda_:  # LM instead of GN
        D = (H.diagonal(dim1=-2, dim2=-1) + 1e-9).diag_embed()
        H = H + D*lambda_
    try:
        P = torch.inverse(H)
    except RuntimeError as e:
        logging.warning(f'Determinant: {torch.det(H)}')
        raise e
    delta = -(P @ g[..., None])[..., 0]
    return delta

def indexing_(feature_map, points):
    '''
    Function gives x and y gradients for 3D points in camera frame.

    inputs: (All pytorch tensors)
    @feature_map : x gradient of the feature map (CxHxW)
    @points : pixel coordinates of points (Nx2)

    outputs: 
    features : features for the points (NxC)
    '''

    features = torch.cat([feature_map[:, i, j].unsqueeze(0) for i, j in zip(points[:,0], points[:,1])])

    return features

In [427]:
n_iters = 100
loss_fn = squared_loss
lambda_ = 0.01

R = R_init
t = t_init

In [432]:
p_3d_1 = (torch.mm(R, pts3D.T).T + t)
p_proj_1 = torch.round(from_homogeneous(torch.mm(K, p_3d_1.T).T)).type(torch.IntTensor)-1
error = indexing_(feature_map_query, torch.flip(p_proj_1,(1,))) - feature_ref
print((error))

tensor([[ -63.],
        [ -34.],
        [ -14.],
        [ -14.],
        [ -28.],
        [  -7.],
        [ -28.],
        [  -7.],
        [ -34.],
        [ -52.],
        [-130.],
        [ -63.],
        [ -28.]], dtype=torch.float64)


In [434]:
i = 0
verbose = 1
p_3d_1 = torch.mm(R, pts3D.T).T + t
p_proj_1 = torch.round(from_homogeneous(torch.mm(K, p_3d_1.T).T)).type(torch.IntTensor)-1
error = indexing_(feature_map_query, torch.flip(p_proj_1,(1,))) - feature_ref
print(error)
cost = 0.5*(error**2).sum(-1)

if i == 0:
    prev_cost = cost.mean(-1)
if verbose:
    print('Iter ', i, cost.mean().item())

tensor([[ -63.],
        [ -34.],
        [ -14.],
        [ -14.],
        [ -28.],
        [  -7.],
        [ -28.],
        [  -7.],
        [ -34.],
        [ -52.],
        [-130.],
        [ -63.],
        [ -28.]], dtype=torch.float64)
Iter  0 1257.5384615384614


In [441]:
J_p_T = torch.cat([
    batched_eye_like(p_3d_1, 3), -skew_symmetric(p_3d_1)], -1)
print("J_p_T is ", J_p_T.shape)
shape = p_3d_1.shape[:-1]
o, z = p_3d_1.new_ones(shape), p_3d_1.new_zeros(shape)
J_e_p = torch.stack([
    o, z, -p_3d_1[..., 0] / p_3d_1[..., 2],
    z, o, -p_3d_1[..., 1] / p_3d_1[..., 2],
], dim=-1).reshape(shape+(2, 3)) / p_3d_1[..., 2, None, None]

print("J_e_p is ", J_e_p.shape)

grad_x_points = indexing_(feature_grad_x, torch.flip(p_proj_1,(1,)))
grad_y_points = indexing_(feature_grad_y, torch.flip(p_proj_1,(1,)))

J_p_F = torch.cat((grad_x_points[..., None], grad_y_points[...,None]), -1)

print("J_p_F is ", J_p_F.shape)
J_e_T = J_p_F @ J_e_p @ J_p_T

Grad = torch.einsum('...ijk,...ij->...ik', J_e_T, error)
Grad = Grad.sum(-2)  # Grad was ... x N x 6

J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])


In [ ]:
J = J_e_T
Hess = torch.einsum('...ijk,...ijl->...ikl', J, J)
# Hess = weights[..., None, None] * Hess
Hess = Hess.sum(-3)  # Hess was ... x N x 6 x 6

delta = optimizer_step(Grad, Hess, lambda_)

dt, dw = delta[..., :3], delta[..., 3:6]
dr = so3exp_map(dw)
print("dr is : ", dw)
print("dt is : ", dt)
R_new = dr @ R
t_new = dr @ t + dt

new_proj_1 = from_homogeneous(pts3D @R_new.T + t_new).type(torch.IntTensor)
new_error = indexing_(feature_map_query, new_proj_1) - feature_ref
new_cost = (new_error**2).sum(-1)
# new_cost = scaled_loss(new_cost, self.loss_fn, scale[..., None])[0]
# new_cost = (confidence*new_cost).mean(-1)
new_cost = new_cost.mean(-1)

lambda_ = np.clip(lambda_ * (10 if new_cost > prev_cost else 1/10),
                  1e-6, 1e2)
# if new_cost > prev_cost:  # cost increased
#     print("cost increased, continue with next iteration")
#     continue
prev_cost = new_cost
R, t = R_new, t_new

In [442]:
i = 0
verbose = 1
p_3d_1 = torch.mm(R, pts3D.T).T + t
p_proj_1 = torch.round(from_homogeneous(torch.mm(K, p_3d_1.T).T)).type(torch.IntTensor)-1
error = indexing_(feature_map_query, torch.flip(p_proj_1,(1,))) - feature_ref
print(error)
cost = 0.5*(error**2).sum(-1)

if i == 0:
    prev_cost = cost.mean(-1)
if verbose:
    print('Iter ', i, cost.mean().item())

J_p_T = torch.cat([
    batched_eye_like(p_3d_1, 3), -skew_symmetric(p_3d_1)], -1)
# print("J_p_T is ", J_p_T)
shape = p_3d_1.shape[:-1]
o, z = p_3d_1.new_ones(shape), p_3d_1.new_zeros(shape)
J_e_p = torch.stack([
    o, z, -p_3d_1[..., 0] / p_3d_1[..., 2],
    z, o, -p_3d_1[..., 1] / p_3d_1[..., 2],
], dim=-1).reshape(shape+(2, 3)) / p_3d_1[..., 2, None, None]

# print("J_e_p is ", J_e_p)

grad_x_points = indexing_(feature_grad_x, torch.flip(p_proj_1,(1,)))
grad_y_points = indexing_(feature_grad_y, torch.flip(p_proj_1,(1,)))

J_p_F = torch.cat((grad_x_points[..., None], grad_y_points[...,None]), -1)

# print("J_p_F is ", J_p_F)
J_e_T = J_p_F @ J_e_p @ J_p_T

Grad = torch.einsum('...ijk,...ij->...ik', J_e_T, error)
# Grad = weights[..., None] * Grad
Grad = Grad.sum(-2)  # Grad was ... x N x 6

J = J_e_T
Hess = torch.einsum('...ijk,...ijl->...ikl', J, J)
# Hess = weights[..., None, None] * Hess
Hess = Hess.sum(-3)  # Hess was ... x N x 6 x 6

delta = optimizer_step(Grad, Hess, lambda_)
# if torch.isnan(delta).any():
#     logging.warning('NaN detected, exit')
#     break
dt, dw = delta[..., :3], delta[..., 3:6]
dr = so3exp_map(dw)
print("dr is : ", dw)
print("dt is : ", dt)
R_new = dr @ R
t_new = dr @ t + dt

new_proj_1 = from_homogeneous(torch.matmul(K, (pts3D @R_new.T + t_new).T).T).type(torch.IntTensor)
new_error = indexing_(feature_map_query, new_proj_1) - feature_ref
new_cost = (new_error**2).sum(-1)
# new_cost = scaled_loss(new_cost, self.loss_fn, scale[..., None])[0]
# new_cost = (confidence*new_cost).mean(-1)
new_cost = new_cost.mean(-1)

lambda_ = np.clip(lambda_ * (10 if new_cost > prev_cost else 1/10),
                  1e-6, 1e2)
# if new_cost > prev_cost:  # cost increased
#     print("cost increased, continue with next iteration")
#     continue
prev_cost = new_cost
R, t = R_new, t_new

tensor([[ -63.],
        [ -34.],
        [ -14.],
        [ -14.],
        [ -28.],
        [  -7.],
        [ -28.],
        [  -7.],
        [ -34.],
        [ -52.],
        [-130.],
        [ -63.],
        [ -28.]], dtype=torch.float64)
Iter  0 1257.5384615384614
J_p_T is  tensor([[[  1.0000,   0.0000,   0.0000,  -0.0000,   1.9287,   5.9906],
         [  0.0000,   1.0000,   0.0000,  -1.9287,  -0.0000, -12.0069],
         [  0.0000,   0.0000,   1.0000,  -5.9906,  12.0069,  -0.0000]],

        [[  1.0000,   0.0000,   0.0000,  -0.0000,   1.7825,  -6.0832],
         [  0.0000,   1.0000,   0.0000,  -1.7825,  -0.0000,  -9.3175],
         [  0.0000,   0.0000,   1.0000,   6.0832,   9.3175,  -0.0000]],

        [[  1.0000,   0.0000,   0.0000,  -0.0000,   2.6854,   8.0988],
         [  0.0000,   1.0000,   0.0000,  -2.6854,  -0.0000,  -4.7485],
         [  0.0000,   0.0000,   1.0000,  -8.0988,   4.7485,  -0.0000]],

        [[  1.0000,   0.0000,   0.0000,  -0.0000,   1.5835,   2.5565],
    

In [445]:
model = sparse3DBA(n_iters = 100, lambda_ = 0.01)

In [446]:
R, t = model(pts3D, feature_ref, feature_map_query, feature_grad_x, feature_grad_y, K, R_init, t_init)

prev cost is  tensor(1933.8077, dtype=torch.float64)
J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([1.4918e-08, 3.5369e-08, 5.9725e-07], dtype=torch.float64)
dt is :  tensor([-1.2929e-06,  3.0137e-06,  1.5405e-06], dtype=torch.float64)
new cost is  tensor(1684.1154, dtype=torch.float64)
prev cost is  tensor(1684.1154, dtype=torch.float64)
J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([3.0738e-08, 2.5108e-08, 6.0976e-07], dtype=torch.float64)
dt is :  tensor([-1.1902e-06,  2.9669e-06,  1.6082e-06], dtype=torch.float64)
new cost is  tensor(1684.1154, dtype=torch.float64)
prev cost is  tensor(1684.1154, dtype=torch.float64)
J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([3.2435e-08, 2.3979e-08, 6.1109e-07], dtype=torch.float64)
dt is :  tensor([-1.1787e-06,  2.9615e-06,  1.6154e-06], dt

prev cost is  tensor(1684.1154, dtype=torch.float64)
J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([3.2635e-08, 2.3842e-08, 6.1124e-07], dtype=torch.float64)
dt is :  tensor([-1.1773e-06,  2.9611e-06,  1.6164e-06], dtype=torch.float64)
new cost is  tensor(1684.1154, dtype=torch.float64)
prev cost is  tensor(1684.1154, dtype=torch.float64)
J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([3.2635e-08, 2.3842e-08, 6.1125e-07], dtype=torch.float64)
dt is :  tensor([-1.1773e-06,  2.9611e-06,  1.6164e-06], dtype=torch.float64)
new cost is  tensor(1684.1154, dtype=torch.float64)
prev cost is  tensor(1684.1154, dtype=torch.float64)
J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([3.2636e-08, 2.3842e-08, 6.1125e-07], dtype=torch.float64)
dt is :  tensor([-1.1773e-06,  2.9611e-06,  1.6164e-06], dt

prev cost is  tensor(1684.1154, dtype=torch.float64)
J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([3.2648e-08, 2.3830e-08, 6.1125e-07], dtype=torch.float64)
dt is :  tensor([-1.1772e-06,  2.9613e-06,  1.6166e-06], dtype=torch.float64)
new cost is  tensor(1684.1154, dtype=torch.float64)
prev cost is  tensor(1684.1154, dtype=torch.float64)
J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([3.2648e-08, 2.3829e-08, 6.1125e-07], dtype=torch.float64)
dt is :  tensor([-1.1772e-06,  2.9613e-06,  1.6166e-06], dtype=torch.float64)
new cost is  tensor(1684.1154, dtype=torch.float64)
prev cost is  tensor(1684.1154, dtype=torch.float64)
J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([3.2649e-08, 2.3829e-08, 6.1125e-07], dtype=torch.float64)
dt is :  tensor([-1.1771e-06,  2.9613e-06,  1.6166e-06], dt

J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([3.2661e-08, 2.3817e-08, 6.1126e-07], dtype=torch.float64)
dt is :  tensor([-1.1770e-06,  2.9615e-06,  1.6168e-06], dtype=torch.float64)
new cost is  tensor(1684.1154, dtype=torch.float64)
prev cost is  tensor(1684.1154, dtype=torch.float64)
J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([3.2662e-08, 2.3816e-08, 6.1126e-07], dtype=torch.float64)
dt is :  tensor([-1.1770e-06,  2.9615e-06,  1.6168e-06], dtype=torch.float64)
new cost is  tensor(1684.1154, dtype=torch.float64)
prev cost is  tensor(1684.1154, dtype=torch.float64)
J_p_T is  torch.Size([13, 3, 6])
J_e_p is  torch.Size([13, 2, 3])
J_p_F is  torch.Size([13, 1, 2])
dr is :  tensor([3.2662e-08, 2.3816e-08, 6.1126e-07], dtype=torch.float64)
dt is :  tensor([-1.1770e-06,  2.9616e-06,  1.6168e-06], dtype=torch.float64)
new cost is  tensor(1684.1154, dty

In [447]:
R

tensor([[ 9.9619e-01, -8.7217e-02,  2.3963e-06],
        [ 8.7217e-02,  9.9619e-01, -3.2446e-06],
        [-2.1042e-06,  3.4412e-06,  1.0000e+00]], dtype=torch.float64)

In [448]:
R_init

tensor([[ 0.9962, -0.0872,  0.0000],
        [ 0.0872,  0.9962,  0.0000],
        [ 0.0000,  0.0000,  1.0000]], dtype=torch.float64)

In [334]:
R_init

tensor([[ 0.9962, -0.0872,  0.0000],
        [ 0.0872,  0.9962,  0.0000],
        [ 0.0000,  0.0000,  1.0000]], dtype=torch.float64)

In [343]:
a = np.random.rand(1,2,3)
b = np.random.rand(1,3,6)
(a @ b).shape

(1, 2, 6)

In [344]:
a

array([[[0.53358027, 0.93631504, 0.01695907],
        [0.73854131, 0.7981811 , 0.70484272]]])

In [345]:
b

array([[[0.99912127, 0.57375511, 0.82709179, 0.8744764 , 0.84867248,
         0.49464652],
        [0.63872462, 0.86594724, 0.12622722, 0.82897161, 0.35695924,
         0.20201891],
        [0.05369191, 0.11775962, 0.78023333, 0.33188607, 0.37115609,
         0.73888152]]])

In [348]:
a[0] @ b[0]

array([[1.13206942, 1.11894092, 0.57274033, 1.24841041, 0.79335565,
        0.46561771],
       [1.2855546 , 1.19792658, 1.26153542, 1.5414339 , 1.17330447,
        1.04735982]])

In [349]:
a @ b

array([[[1.13206942, 1.11894092, 0.57274033, 1.24841041, 0.79335565,
         0.46561771],
        [1.2855546 , 1.19792658, 1.26153542, 1.5414339 , 1.17330447,
         1.04735982]]])